### ISSUE TITLE
レーンをクリックしたときにテキストのフォーカスを外してほしい

### ISSUE THREAD

**Issue by einst-alfimi** [Nekokan/BMSE#4]
レーンに対してクリックした際にテキストのフォーカスを外してほしい。

全選択（Ctrl+A）や選択したものを削除するDeleteキーについて、`#TITLE`などのテキストエリアにフォーカスが当たってる状態だとテキスト編集が優先されてしまい、レーン側に対する入力が反応しなくなる(テキスト編集でも意味のあるキーなので当然)。

別件で、テキストにフォーカスが当たっていると右クリックメニューのDeleteなども動作しなくなってしまう。

バージョン2.1.0で確認

**Comment by Nekokan** [comment]
報告ありがとうございます。
レーンクリックでフォーカスが外れるよう修正しました。（v2.1.1）
別件についてもこれで修正されたかと思います。ご確認ください。

**Comment by einst-alfimi** [comment]
修正確認しました！対応ありがとうございました。
