### ISSUE TITLE
変換ウィザードの「使用していない定義を消去」が使用されている定義を消してしまう

### ISSUE THREAD

**Issue by OtterSou** [Nekokan/BMSE#5]
v2.1.2にて、変換ウィザードの「使用していない#WAV・#BMP・#BGAの定義を消去」を実行すると、使用されているにもかかわらず消えてしまう定義が多数あり、この状態でBMSを再生するとかなりの音が再生されなくなります。
(アンドゥはできます)
具体的にどの定義が消えるかの条件はよくわかりません。

**Comment by Nekokan** [comment]
v2.1.3にて修正しました。
変換ウィザードの「使用していない#WAV・#BMP・#BGAの定義を消去」のほか「定義リストの整列」も
v2.0.0から正しく動作していませんでした。
報告ありがとうございました。
